version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d taskdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/taskdb
      SECRET_KEY: your-super-secret-key-change-this-in-production
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./app:/app/app
      - ./frontend:/app/frontend

volumes:
  postgres_data: